# Generated by Django 3.2.15 on 2022-09-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Entwurf'), ('PUBLISHED', 'Veroeffentlicht')], default='DRAFT', max_length=50, verbose_name='Status')),
                ('title', models.CharField(max_length=250, verbose_name='Titel')),
                ('sub_title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Untertitel')),
                ('image', models.ImageField(upload_to='blog/cover_images/', verbose_name='Cover Image')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Blog Inhalt')),
                ('slug', models.SlugField(blank=True, help_text='Titel als Url', null=True, verbose_name='Slug')),
                ('published_on', models.DateTimeField(blank=True, null=True, verbose_name='Veroeffentlich am')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-created_on'],
                'get_latest_by': ['-created_on'],
            },
        ),
    ]
