# Generated by Django 3.2.15 on 2022-09-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Titel')),
                ('alt_text', models.TextField(blank=True, null=True, verbose_name='Bschreibung')),
                ('image', models.ImageField(upload_to='blog/images', verbose_name='Bild')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Post Bild',
                'verbose_name_plural': 'Post Bilder',
            },
        ),
    ]
